spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: 'jdbc:h2:mem:sq-quick-start'
    username: 'sa'
    password: ''

tenants:
  datasources:
    vw:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: 'jdbc:mysql://localhost:3306/vw'
      username: 'root'
      password: ''
    bmw:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: 'jdbc:mysql://localhost:3306/bmw'
      username: 'root'
      password: ''
    toyota:
      driverClassName: com.mysql.cj.jdbc.Driver
      jdbcUrl: 'jdbc:mysql://localhost:3306/toyota'
      username: 'root'
      password: ''